cluster:
  name: {{CLUSTER_NAME}}
node:
  master: {{NODE_MASTER | default("true")}}
  data: {{NODE_DATA | default("true")}}
  name: "{{NODE_NAME}}"
  ingest: true
  max_local_storage_nodes: 1

network:
  host: _site_
  publish_host: "{{inventory_hostname}}"
  
transport.tcp.port: 9300

path:
  data: "{{es_data_vol}}/data"
  logs: "{{es_data_vol}}/log"
  
bootstrap:
  memory_lock: true
  
http:
  enabled: {{ HTTP_ENABLE | default("false") }}
  compression: true
  cors:
    enabled: true
    allow-origin: "*"

discovery:
  zen:
    ping.unicast.hosts: "{{discovery_hosts}}"
    minimum_master_nodes: {{NUMBER_OF_MASTERS | default(1)}}

xpack.security.enabled: false