- name: Install Elastic nodes
  become: true
  hosts: role=worker
  vars:
    master_nodes: "{{play_hosts[0:2]}}"
    data_nodes: "{{play_hosts[2:]}}"
    client_nodes: "{{play_hosts[2:]}}"
    kibana_node: "{{play_hosts[-1]}}"
    discovery_hosts: "{{master_nodes | join(',')}}"
    plat_folder: "{{lookup('env', 'PLAT_BASE')}}"
    deployment_type: "docker"
    start_elastic_yml: "start_master_{{deployment_type}}.yml"
    force_install: false

  tasks:
    - include_vars: elasticsearch_defaults.yml
   
    # Start MASTER
    - name: Start master node container
      when: inventory_hostname in master_nodes
      include: "{{start_elastic_yml}}"
      static: no
      vars:
        container_name: "es_master"
        es_data_vol: "{{data_path}}/{{container_name}}"
        NODE_MASTER: "true"
        NODE_DATA: "false"
      tags: ["master"]
        
        
    # Start DATA only
    - name: Start data node container
      when: inventory_hostname in data_nodes
      include: "{{start_elastic_yml}}"
      static: no
      vars:
        container_name: "es_data"
        es_data_vol: "{{data_path}}/{{container_name}}"
        NODE_MASTER: "false"
        NODE_DATA: "true"
      tags: ["data"]
     

    # Start CLIENT
    - name: Start client node container
      when: inventory_hostname in client_nodes
      include: start_client.yml
      static: no
      vars:
        container_name: "es_client"
        es_data_vol: "{{data_path}}/{{container_name}}"
        discovery_hosts: "{{master_nodes|map('regex_replace', '^(.*)$', '\\1:9300' ) | join(',')}}"
      tags: ["client"]
        
        
    - name: Consul checks install
      include: "{{plat_folder}}/mantl/playbooks/install-consul-checks.yml"
      when: inventory_hostname in client_nodes
      static: no
      vars:
        config:
          - {src: "../files/es_client_consul.json", dest: "es_client-consul.json"}
      tags: ["client"]

      
    # start Kibana
    - name: Start Kibana container
      when: inventory_hostname == kibana_node
      include: start_kibana.yml
      static: no
      vars:
        kibana_port: "31100"
      tags: ["kibana"]
      
    - name: Consul checks install
      include: "{{plat_folder}}/mantl/playbooks/install-consul-checks.yml"
      when: inventory_hostname == kibana_node
      static: no
      vars:
        config:
          - {src: "../files/kibana_consul.json", dest: "kibana-consul.json"}
      tags: ["kibana"]
  
  
    # start Curator
    - name: Start Curator container
      when: inventory_hostname == kibana_node
      include: start_curator.yml
      static: no
      tags: ["curator"]
      
    - name: copy curator config file
      sudo: yes
      copy: src=../files/delete_data.yml dest=/curator
      tags: ["curator"]
      
      