# make sure our docker image will not be removed by docker-gc
- name: Retrieve the docker images-exclude file
  hosts: role=control[0]
  become: true
  tasks:
    - name: get container ids
      shell: "docker images -q {{item}} >> /tmp/images-ids"
      with_items: 
        - "csf/elk_e:5.4"
        - "csf/elk_k:5.4"
 
    - name: add container ids to facts
      shell: "cat /tmp/images-ids"
      register: images_ids_output
      
    - name: remove tmp file
      file:  
        path: /tmp/images-ids
        state: absent
      
    - set_fact:
        elk_container_ids: "{{images_ids_output.stdout_lines}}"
        
    - name: append id to excluded ids
      when: elk_container_id is defined 
      with_items: "{{elk_container_ids}}"
      lineinfile:
        dest: /etc/docker/images-exclude
        line: "{{item}}"
        state: present

    - name: fetch docker images ids to localhost
      become: true
      fetch:
        src: /etc/docker/images-exclude
        dest: /tmp/images-exclude
        flat: yes

 
 # disable old ELK consul checks
- name: "disable old consul checks"
  hosts: role=control
  become: true
  vars:
    plat_folder: "{{lookup('env', 'PLAT_BASE')}}"

  tasks:
    - name: Consul checks install
      include: "{{plat_folder}}/mantl/playbooks/install-consul-checks.yml"
      static: no
      vars:
        config:
          - {src: "../files/marathon_consul.json", dest: "marathon.json"}

    
        

- name: prepare hosts for Elasticsearch containers
  hosts: role=worker
  become: true
  vars:
    ia_ip: "{{lookup('env', 'LOCALHOST_IP')}}"
    remove_containers: true
    remove_data: false
 
  tasks:
    - include_vars: elasticsearch_defaults.yml
   
    - name: "Install ansible modules: docker-py"
      pip:
        state: present
        name: "docker-py"
        version: "1.10.6"
        extra_args: "--trusted-host {{ia_ip}} --no-index -f {{SOFTWARE_REPOSITORY}}/external_images/py"
  
  
    - name: "System configuration: vm.swappiness" 
      sysctl:
        name: vm.swappiness
        value: 1
        state: present
        sysctl_set: yes
        
        
    - name: "System configuration: vm.max_map_count" 
      sysctl:
        name: vm.max_map_count
        value: 262144
        state: present
        sysctl_set: yes
        
 
 
    - name: "Copy the docker images-exclude file"
      copy:
        dest: "/etc/docker/images-exclude"
        src: "/tmp/images-exclude"
 
 
    - name: "remove elasticsearch-cliet and kibana checks"
      become: true
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - "/etc/consul/es_client-consul.json"
        - "/etc/consul/kibana-consul.json"

        
    - name: "reload consul"
      become: true
      shell: "consul reload"
        
    - name: cleanup old containers
      when: remove_containers == true
      docker_container:
        name: "{{item}}"
        state: absent
      with_items:
        - es_master
        - es_data
        - es_client
        - kibana
        - curator

    - name: stop all running elasticsearch deemons
      when: remove_containers
      become: true
      ignore_errors: yes
      shell: |
        if [[ -f {{ES_HOME}}/pid.file ]]; then
            kill -15 $(< {{ES_HOME}}/pid.file )
        fi
        
    - name: remove all data
      when: remove_data
      become: true
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - "{{data_path}}"
        - "/var/lib/mesos/elk"
 