---


- name: cleanup old containers
  docker_container:
    name: "{{container_name}}"
    state: absent

    
    
- name: Initialize data directory
  file:
    path: "{{item}}"
    state: directory
    mode: 0777
  with_items:
    - "{{es_data_vol}}/data"
    - "{{es_data_vol}}/log"


    
- name: "Start {{container_name}} container"
  docker_container:
    name: "{{container_name}}"
    image: csf/elk_e:5.4
    state: started
    pull: false
    volumes:
    - "{{es_data_vol}}:/data"
    ports:
    - "9300:9300"
    capabilities:
    - IPC_LOCK
    memory: 8g
    memory_swap: 8g
    memory_swappiness: 0
    ulimits:
     - nofile:65536:65536
     - memlock:-1:-1
     - nproc:2048:2048
    env:
      NODE_NAME: "{{inventory_hostname}}.{{container_name}}"
      CLUSTER_NAME: "{{CLUSTER_NAME}}"
      NODE_MASTER: "{{NODE_MASTER}}"
      NODE_DATA: "{{NODE_DATA}}"
      NODE_INGEST: "true"
      NETWORK_HOST: "_site_"
      HTTP_ENABLE: "false"
      ES_JAVA_OPTS: "-Xms4g -Xmx4g"
      NUMBER_OF_SHARDS: "1"
      NUMBER_OF_REPLICAS: "1"
      NUMBER_OF_MASTERS: "1"
      DISCOVERY_SERVICE: "{{discovery_hosts}}"
      xpack.security.enabled: "false"
      network.publish_host: "{{inventory_hostname}}"
      bootstrap.memory_lock: "true"
      transport.tcp.port: "9300"

